<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Library</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>Preview</LangVersion>
    </PropertyGroup>

    <PropertyGroup>
        <Version>0.1.0</Version>
        <FileVersion>$(Version)</FileVersion>
        <AssemblyVersion>$(Version)</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\KitX Standard\KitX Contracts\KitX.Contract.CSharp\KitX.Contract.CSharp.csproj" />
    </ItemGroup>

</Project>
